blank_issues_enabled: false
contact_links:
  - name: Foodie Hosted/Demo
    url: https://foodie.tjm.sk
    about: Try it out yourself before deploying
  - name: PM/Developer
    url: https://jakubdobos.eu
    about: Actual code was 100% written by Claude from Anthropic
